feat: API呼び出しのラッパーを作成
traP-jp/h24s_24 pull request #36
Opened 2024-06-15 13:51 UTC by cp-20

2024-06-15 14:02 UTC, ikura-hamu requested changes
2点お願いします。
これは疑問なんだけどuuid型っていうのは無い？

2024-06-15 14:02 UTC, ikura-hamu commented on frontend/src/features/api.ts
> +  parent_id?: string;
?ってoptionalだっけ。parent_idはrequiredになりました。親が無い時は自身のIDが入ります

2024-06-15 14:02 UTC, ikura-hamu commented on frontend/src/features/api.ts
> +export const getUser = async (userId: string) => {
`userId`じゃなくて`userName`かな

2024-06-15 14:31 UTC, cp-20 commented
作ればあります

2024-06-15 15:30 UTC, ikura-hamu commented
無いならいいよ(Goはあるけどどうなんだろうと思っただけ)

2024-06-16 00:16 UTC, ikura-hamu approved these changes

2024-06-16 00:16 UTC, merged