fix: 親投稿が正しく取得されないバグの修正
traP-jp/h24s_24 pull request #93
Opened 2024-06-16 15:02 UTC by cp-20

2024-06-16 15:51 UTC, ikura-hamu requested changes
でかクエリありがとう

2024-06-16 15:51 UTC, ikura-hamu commented on backend/repository/post.go
> +		"FROM posts WHERE id = ? AND id <> ? AND id <> ?;", p.ParentID, p.RootID, p.ID, p.ParentID)
古い順に並べたいのであれば、ここに`ORDER BY created_at ASC`をつけれreverseいらんくなる気がする

2024-06-16 15:52 UTC, cp-20 commented on backend/repository/post.go
> +		"FROM posts WHERE id = ? AND id <> ? AND id <> ?;", p.ParentID, p.RootID, p.ID, p.ParentID)
そうかも (UNION使ってるのでそれだけの修正では済まなさそうだけど、実現できそうな気がする)

2024-06-17 11:14 UTC, ikura-hamu approved these changes
ok

2024-06-17 14:02 UTC, merged